version: "3"
services:
  device_manager:
    image: vladx09/clickpecker-device-manager:latest_nosrc
    volumes:
      - "./clickpecker-device-manager:/srv"
    network_mode: "host"
    container_name: device_manager 

  pytest_worker:
    image: vladx09/clickpecker-library:latest_nosrc
    volumes:
      - "./clickpecker-library:/clickpecker"
      - "./clickpecker-pytest:/clickpecker-pytest"
      - "./clickpecker-pytest/examples:/workdir"
    depends_on:
      - device_manager
    container_name: pytest_worker
    network_mode: "host"
